site_name: Project Data Dictionary
theme:
  name: material
  language: en
  features:
    - navigation.tabs # Crea tab in alto per le sezioni principali
    - navigation.sections # Raggruppa le voci nel menu laterale
    - search.suggest # Suggerimenti durante la ricerca
    - content.code.copy # Permette di copiare query di esempio

plugins:
  - search
  - i18n:
      docs_structure: suffix # Indica che userai file come nome.en.md
      languages:
        - locale: it
          name: Italiano
          build: true
        - locale: en
          default: true
          name: English
          build: true

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Home: index.md
  - Overview of the schema (ER): schema_er.md
  - Data Dictionary:
    - Users and access control:
      - User groups: tables/users.md
      - Roles: tables/roles.md
    - Entities and relationships:
      - Locations: tables/locations.md
  - Contribution Guidelines: guidelines.md

